name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar el acceso SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-54-81-81-82.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      # Desplegar el código en la instancia EC2
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-54-81-81-82.compute-1.amazonaws.com << 'EOF'
            # Preparar la instancia
            sudo apt-get update
            sudo apt-get install -y git nodejs npm
            sudo npm install -g pm2

            # Clonar el repositorio si no existe
            if [ ! -d "/home/ubuntu/HelloWorldJavaBalancer" ]; then
                git clone <URL_DEL_REPOSITORIO> /home/ubuntu/HelloWorldJavaBalancer
            fi
            cd /home/ubuntu/HelloWorldJavaBalancer

            # Asegurarse de tener los últimos cambios
            git fetch origin
            git reset --hard origin/main

            # Instalar dependencias de npm
            npm install

            # Usar PM2 para iniciar/reiniciar el servidor
            pm2 stop HelloWorldJavaBalancer || true
            pm2 start index.js --name "HelloWorldJavaBalancer"
            pm2 save

            # Verificar que el servidor esté ejecutándose
            pm2 list
          EOF
