name: Deploy Program02 to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Program02 to EC2
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar el acceso SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Desplegar a cada servidor EC2
      - name: Deploy to EC2 Instance 1
        run: |
          ssh-keyscan -H ${{ secrets.INSTANCE1_DNS }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.INSTANCE1_DNS }} << 'EOF'
            sudo apt-get update
            sudo apt-get install -y npm
            sudo npm install -g pm2
            cd /home/${{ secrets.USERNAME }} || mkdir -p /home/${{ secrets.USERNAME }}
            cd /home/${{ secrets.USERNAME }}/HelloWorldJavaBalancer || git clone https://github.com/MarcosSuntaxi/HelloWorldJavaBalancer HelloWorldJavaBalancer
            cd /home/${{ secrets.USERNAME }}/HelloWorldJavaBalancer
            git reset --hard
            git pull origin main
            npm install
            pm2 start index.js --name "HelloWorldJavaBalancer" || pm2 restart "HelloWorldJavaBalancer"
            pm2 save
          EOF

      - name: Deploy to EC2 Instance 2
        run: |
          ssh-keyscan -H ${{ secrets.INSTANCE2_DNS }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.INSTANCE2_DNS }} << 'EOF'
            sudo apt-get update
            sudo apt-get install -y npm
            sudo npm install -g pm2
            cd /home/${{ secrets.USERNAME }} || mkdir -p /home/${{ secrets.USERNAME }}
            cd /home/${{ secrets.USERNAME }}/HelloWorldJavaBalancer || git clone https://github.com/MarcosSuntaxi/HelloWorldJavaBalancer HelloWorldJavaBalancer
            cd /home/${{ secrets.USERNAME }}/HelloWorldJavaBalancer
            git reset --hard
            git pull origin main
            npm install
            pm2 start index.js --name "HelloWorldJavaBalancer" || pm2 restart "HelloWorldJavaBalancer"
            pm2 save
          EOF

      - name: Deploy to EC2 Instance 3
        run: |
          ssh-keyscan -H ${{ secrets.INSTANCE3_DNS }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.INSTANCE3_DNS }} << 'EOF'
            sudo apt-get update
            sudo apt-get install -y npm
            sudo npm install -g pm2
            cd /home/${{ secrets.USERNAME }} || mkdir -p /home/${{ secrets.USERNAME }}
            cd /home/${{ secrets.USERNAME }}/HelloWorldJavaBalancer || git clone https://github.com/MarcosSuntaxi/HelloWorldJavaBalancer.git HelloWorldJavaBalancer
            cd /home/${{ secrets.USERNAME }}/HelloWorldJavaBalancer
            git reset --hard
            git pull origin main
            npm install
            pm2 start index.js --name "HelloWorldJavaBalancer" || pm2 restart "HelloWorldJavaBalancer"
            pm2 save
          EOF

      - name: Deploy to EC2 Instance 4
        run: |
          ssh-keyscan -H ${{ secrets.INSTANCE4_DNS }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.INSTANCE4_DNS }} << 'EOF'
            sudo apt-get update
            sudo apt-get install -y npm
            sudo npm install -g pm2
            cd /home/${{ secrets.USERNAME }} || mkdir -p /home/${{ secrets.USERNAME }}
            cd /home/${{ secrets.USERNAME }}/HelloWorldJavaBalancer || git clone https://github.com/MarcosSuntaxi/HelloWorldJavaBalancer.git HelloWorldJavaBalancer
            cd /home/${{ secrets.USERNAME }}/HelloWorldJavaBalancer
            git reset --hard
            git pull origin main
            npm install
            pm2 start index.js --name "HelloWorldJavaBalancer" || pm2 restart "HelloWorldJavaBalancer"
            pm2 save
          EOF
